# Automatic build testing with Bitbucket pipeline 

pipelines:

   default:
      - step:
              caches:
                  - docker
              name: Build dependency image openMPI
              script:
                   - docker build --target openmpi  -f DockerfileDependencies .
      - step:
              caches:
                  - docker
              name: Build dependency image cmake
              script:
                  - docker build --target cmake -f DockerfileDependencies .
      - step:
              caches:
                  - docker
              name: Build dependency image
              script:
                  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
                  - docker build -t iheartpolimi/lifev-dependencies-image:latest -f DockerfileDependencies .
                  - docker push iheartpolimi/lifev-dependencies-image:latest
      - step:
              name: Build LifeV-Build image
              script:
                  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
                  - docker build -t iheartpolimi/lifev-build-image:latest -f DockerfileBuildLifeV .
                  - docker push iheartpolimi/lifev-build-image:latest

options:
  docker: true


          
