# Automatic build testing with Bitbucket pipeline 

pipelines:

   default:
      - step:
              caches:
                  - docker
              name: Build dependency partial image (openMPI cmake VTK)
              script:
                  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
                  - docker build -t iheartpolimi/test:lifev-dependencies-partial-image-candidate -f DockerfileDependenciesPartial .
                  - docker push iheartpolimi/test:lifev-dependencies-partial-image-candidate
      - step:
              caches:
                  - docker
              name: Build dependency image
              script:
                  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
                  - docker build -t iheartpolimi/test:lifev-dependencies-image-candidate -f DockerfileDependencies .
                  - docker push iheartpolimi/test:lifev-dependencies-image-candidate
      - step:
              name: Build LifeV-Build image
              script:
                  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
                  - docker build -t iheartpolimi/test:lifev-build-image-candidate -f DockerfileBuildLifeV .
                  - docker push iheartpolimi/test:lifev-build-image-candidate

options:
  docker: true


          
