# Automatic build testing with Bitbucket pipeline 

pipelines:
  default:
      - step:
              caches:
                  - docker
                  - libsource
                  - libpackages
                  - libbuilds

              name: Build dependency image
              script:
                  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
                  - docker build -t iheartpolimi/test:lifev-dependencies-image -f DockerfileDependencies .
                  - docker push iheartpolimi/test:lifev-dependencies-image
      - step:
              name: Build LifeV-Build image
              script:
                  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
                  - docker build -t iheartpolimi/test:lifev-build-image -f DockerfileBuildLifeV .
                  - docker push iheartpolimi/test:lifev-build-image

options:
  docker: true

definitions:
  caches:
          libsource: /development/libs/sources
          libpackages: /development/libs/packages
          libbuilds: /development/libs/builds
           
